### ISSUE TITLE
Inconsistent this result

### ISSUE THREAD

**Issue by ifyour** [jaywcjlove/local-ip-url#1]
![image](https://user-images.githubusercontent.com/15377484/41771964-7967dba8-7649-11e8-9864-fcde310c55a3.png)

**Comment by jaywcjlove** [comment]
@ifyour from windows ?

**Comment by ifyour** [comment]
@jaywcjlove yap.. need more detail?

**Comment by jaywcjlove** [comment]
@ifyour Later, I debug it.

**Comment by jaywcjlove** [comment]
@ifyour windows 10 ? There are no problems with linux and Mac.

**Comment by ifyour** [comment]
@jaywcjlove This is Windows 7 Enterprise Edition. :confused:

**Comment by jaywcjlove** [comment]
@ifyour My test returned is correct.

> node v8.11.3  
> Windows 10  

![image](https://user-images.githubusercontent.com/1680273/41816132-61723f5e-77af-11e8-8eca-895d9c112bd0.png)
