### ISSUE TITLE
Invalid type declaration?

### ISSUE THREAD

**Issue by aommm** [jaywcjlove/local-ip-url#5]
Hi!

After upgrading to version 1.0.6 I am getting type errors. I see that `index.d.ts` contains the following:

```
function localIpUrl(name?: 'public' | 'private', family?: 'ipv4' | 'ipv6'): void;

export = localIpUrl
```

Is this correct? My code expects the function to return `string` instead of `void`.

Thanks in advance!

**Comment by jaywcjlove** [comment]
@aommm Upgrade `v1.0.7`

**Comment by aommm** [comment]
Wonderful, thanks for the quick turnaround!
